using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Reflection;
using Materialize.Reify2.Transitions;

namespace Materialize.Reify2.Parsing2.SeqMethods 
{
	static partial class QyParser 
	{
		delegate Transition Handler(MethodCallExpression ex);
		
		static IDictionary<MethodInfo, Handler> _dHandlers 
			= new Dictionary<MethodInfo, Handler>() {
				{ QyMethods.Aggregate, ex => new AggregateTransition(ex) },
				{ QyMethods.Aggregate2, ex => new Aggregate2Transition(ex) },
				{ QyMethods.Aggregate3, ex => new Aggregate3Transition(ex) },
				{ QyMethods.All, ex => new AllTransition(ex) },
				{ QyMethods.Any, ex => new AnyTransition(ex) },
				{ QyMethods.Any2, ex => new Any2Transition(ex) },
				{ QyMethods.Average, ex => new AverageTransition(ex) },
				{ QyMethods.Average10, ex => new Average10Transition(ex) },
				{ QyMethods.Average11, ex => new Average11Transition(ex) },
				{ QyMethods.Average12, ex => new Average12Transition(ex) },
				{ QyMethods.Average13, ex => new Average13Transition(ex) },
				{ QyMethods.Average14, ex => new Average14Transition(ex) },
				{ QyMethods.Average15, ex => new Average15Transition(ex) },
				{ QyMethods.Average16, ex => new Average16Transition(ex) },
				{ QyMethods.Average17, ex => new Average17Transition(ex) },
				{ QyMethods.Average18, ex => new Average18Transition(ex) },
				{ QyMethods.Average19, ex => new Average19Transition(ex) },
				{ QyMethods.Average2, ex => new Average2Transition(ex) },
				{ QyMethods.Average20, ex => new Average20Transition(ex) },
				{ QyMethods.Average3, ex => new Average3Transition(ex) },
				{ QyMethods.Average4, ex => new Average4Transition(ex) },
				{ QyMethods.Average5, ex => new Average5Transition(ex) },
				{ QyMethods.Average6, ex => new Average6Transition(ex) },
				{ QyMethods.Average7, ex => new Average7Transition(ex) },
				{ QyMethods.Average8, ex => new Average8Transition(ex) },
				{ QyMethods.Average9, ex => new Average9Transition(ex) },
				{ QyMethods.Cast, ex => new CastTransition(ex) },
				{ QyMethods.Concat, ex => new ConcatTransition(ex) },
				{ QyMethods.Contains, ex => new ContainsTransition(ex) },
				{ QyMethods.Contains2, ex => new Contains2Transition(ex) },
				{ QyMethods.Count, ex => new CountTransition(ex) },
				{ QyMethods.Count2, ex => new Count2Transition(ex) },
				{ QyMethods.DefaultIfEmpty, ex => new DefaultIfEmptyTransition(ex) },
				{ QyMethods.DefaultIfEmpty2, ex => new DefaultIfEmpty2Transition(ex) },
				{ QyMethods.Distinct, ex => new DistinctTransition(ex) },
				{ QyMethods.Distinct2, ex => new Distinct2Transition(ex) },
				{ QyMethods.ElementAt, ex => new ElementAtTransition(ex) },
				{ QyMethods.ElementAtOrDefault, ex => new ElementAtOrDefaultTransition(ex) },
				{ QyMethods.Except, ex => new ExceptTransition(ex) },
				{ QyMethods.Except2, ex => new Except2Transition(ex) },
				{ QyMethods.First, ex => new FirstTransition(ex) },
				{ QyMethods.First2, ex => new First2Transition(ex) },
				{ QyMethods.FirstOrDefault, ex => new FirstOrDefaultTransition(ex) },
				{ QyMethods.FirstOrDefault2, ex => new FirstOrDefault2Transition(ex) },
				{ QyMethods.GroupBy, ex => new GroupByTransition(ex) },
				{ QyMethods.GroupBy2, ex => new GroupBy2Transition(ex) },
				{ QyMethods.GroupBy3, ex => new GroupBy3Transition(ex) },
				{ QyMethods.GroupBy4, ex => new GroupBy4Transition(ex) },
				{ QyMethods.GroupBy5, ex => new GroupBy5Transition(ex) },
				{ QyMethods.GroupBy6, ex => new GroupBy6Transition(ex) },
				{ QyMethods.GroupBy7, ex => new GroupBy7Transition(ex) },
				{ QyMethods.GroupBy8, ex => new GroupBy8Transition(ex) },
				{ QyMethods.GroupJoin, ex => new GroupJoinTransition(ex) },
				{ QyMethods.GroupJoin2, ex => new GroupJoin2Transition(ex) },
				{ QyMethods.Intersect, ex => new IntersectTransition(ex) },
				{ QyMethods.Intersect2, ex => new Intersect2Transition(ex) },
				{ QyMethods.Join, ex => new JoinTransition(ex) },
				{ QyMethods.Join2, ex => new Join2Transition(ex) },
				{ QyMethods.Last, ex => new LastTransition(ex) },
				{ QyMethods.Last2, ex => new Last2Transition(ex) },
				{ QyMethods.LastOrDefault, ex => new LastOrDefaultTransition(ex) },
				{ QyMethods.LastOrDefault2, ex => new LastOrDefault2Transition(ex) },
				{ QyMethods.LongCount, ex => new LongCountTransition(ex) },
				{ QyMethods.LongCount2, ex => new LongCount2Transition(ex) },
				{ QyMethods.Max, ex => new MaxTransition(ex) },
				{ QyMethods.Max2, ex => new Max2Transition(ex) },
				{ QyMethods.Min, ex => new MinTransition(ex) },
				{ QyMethods.Min2, ex => new Min2Transition(ex) },
				{ QyMethods.OfType, ex => new OfTypeTransition(ex) },
				{ QyMethods.OrderBy, ex => new OrderByTransition(ex) },
				{ QyMethods.OrderBy2, ex => new OrderBy2Transition(ex) },
				{ QyMethods.OrderByDescending, ex => new OrderByDescendingTransition(ex) },
				{ QyMethods.OrderByDescending2, ex => new OrderByDescending2Transition(ex) },
				{ QyMethods.Reverse, ex => new ReverseTransition(ex) },
				{ QyMethods.Select, ex => new SelectTransition(ex) },
				{ QyMethods.Select2, ex => new Select2Transition(ex) },
				{ QyMethods.SelectMany, ex => new SelectManyTransition(ex) },
				{ QyMethods.SelectMany2, ex => new SelectMany2Transition(ex) },
				{ QyMethods.SelectMany3, ex => new SelectMany3Transition(ex) },
				{ QyMethods.SelectMany4, ex => new SelectMany4Transition(ex) },
				{ QyMethods.SequenceEqual, ex => new SequenceEqualTransition(ex) },
				{ QyMethods.SequenceEqual2, ex => new SequenceEqual2Transition(ex) },
				{ QyMethods.Single, ex => new SingleTransition(ex) },
				{ QyMethods.Single2, ex => new Single2Transition(ex) },
				{ QyMethods.SingleOrDefault, ex => new SingleOrDefaultTransition(ex) },
				{ QyMethods.SingleOrDefault2, ex => new SingleOrDefault2Transition(ex) },
				{ QyMethods.Skip, ex => new SkipTransition(ex) },
				{ QyMethods.SkipWhile, ex => new SkipWhileTransition(ex) },
				{ QyMethods.SkipWhile2, ex => new SkipWhile2Transition(ex) },
				{ QyMethods.Sum, ex => new SumTransition(ex) },
				{ QyMethods.Sum10, ex => new Sum10Transition(ex) },
				{ QyMethods.Sum11, ex => new Sum11Transition(ex) },
				{ QyMethods.Sum12, ex => new Sum12Transition(ex) },
				{ QyMethods.Sum13, ex => new Sum13Transition(ex) },
				{ QyMethods.Sum14, ex => new Sum14Transition(ex) },
				{ QyMethods.Sum15, ex => new Sum15Transition(ex) },
				{ QyMethods.Sum16, ex => new Sum16Transition(ex) },
				{ QyMethods.Sum17, ex => new Sum17Transition(ex) },
				{ QyMethods.Sum18, ex => new Sum18Transition(ex) },
				{ QyMethods.Sum19, ex => new Sum19Transition(ex) },
				{ QyMethods.Sum2, ex => new Sum2Transition(ex) },
				{ QyMethods.Sum20, ex => new Sum20Transition(ex) },
				{ QyMethods.Sum3, ex => new Sum3Transition(ex) },
				{ QyMethods.Sum4, ex => new Sum4Transition(ex) },
				{ QyMethods.Sum5, ex => new Sum5Transition(ex) },
				{ QyMethods.Sum6, ex => new Sum6Transition(ex) },
				{ QyMethods.Sum7, ex => new Sum7Transition(ex) },
				{ QyMethods.Sum8, ex => new Sum8Transition(ex) },
				{ QyMethods.Sum9, ex => new Sum9Transition(ex) },
				{ QyMethods.Take, ex => new TakeTransition(ex) },
				{ QyMethods.TakeWhile, ex => new TakeWhileTransition(ex) },
				{ QyMethods.TakeWhile2, ex => new TakeWhile2Transition(ex) },
				{ QyMethods.ThenBy, ex => new ThenByTransition(ex) },
				{ QyMethods.ThenBy2, ex => new ThenBy2Transition(ex) },
				{ QyMethods.ThenByDescending, ex => new ThenByDescendingTransition(ex) },
				{ QyMethods.ThenByDescending2, ex => new ThenByDescending2Transition(ex) },
				{ QyMethods.Union, ex => new UnionTransition(ex) },
				{ QyMethods.Union2, ex => new Union2Transition(ex) },
				{ QyMethods.Where, ex => new WhereTransition(ex) },
				{ QyMethods.Where2, ex => new Where2Transition(ex) },
				{ QyMethods.Zip, ex => new ZipTransition(ex) },
			};

	} 

}