using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Reflection;
using Materialize.Reify2.Transitions;

namespace Materialize.Reify2.Parsing2.SeqMethods 
{
	static partial class QyParser 
	{
		delegate ITransition Handler(MethodCallExpression ex);
		
		static IDictionary<MethodInfo, Handler> _dHandlers 
			= new Dictionary<MethodInfo, Handler>() {
				{ QyMethods.Aggregate, AggregateTransition.Create },
				{ QyMethods.Aggregate2, Aggregate2Transition.Create },
				{ QyMethods.Aggregate3, Aggregate3Transition.Create },
				{ QyMethods.All, AllTransition.Create },
				{ QyMethods.Any, AnyTransition.Create },
				{ QyMethods.Any2, Any2Transition.Create },
				{ QyMethods.Average, AverageTransition.Create },
				{ QyMethods.Average10, Average10Transition.Create },
				{ QyMethods.Average11, Average11Transition.Create },
				{ QyMethods.Average12, Average12Transition.Create },
				{ QyMethods.Average13, Average13Transition.Create },
				{ QyMethods.Average14, Average14Transition.Create },
				{ QyMethods.Average15, Average15Transition.Create },
				{ QyMethods.Average16, Average16Transition.Create },
				{ QyMethods.Average17, Average17Transition.Create },
				{ QyMethods.Average18, Average18Transition.Create },
				{ QyMethods.Average19, Average19Transition.Create },
				{ QyMethods.Average2, Average2Transition.Create },
				{ QyMethods.Average20, Average20Transition.Create },
				{ QyMethods.Average3, Average3Transition.Create },
				{ QyMethods.Average4, Average4Transition.Create },
				{ QyMethods.Average5, Average5Transition.Create },
				{ QyMethods.Average6, Average6Transition.Create },
				{ QyMethods.Average7, Average7Transition.Create },
				{ QyMethods.Average8, Average8Transition.Create },
				{ QyMethods.Average9, Average9Transition.Create },
				{ QyMethods.Cast, CastTransition.Create },
				{ QyMethods.Concat, ConcatTransition.Create },
				{ QyMethods.Contains, ContainsTransition.Create },
				{ QyMethods.Contains2, Contains2Transition.Create },
				{ QyMethods.Count, CountTransition.Create },
				{ QyMethods.Count2, Count2Transition.Create },
				{ QyMethods.DefaultIfEmpty, DefaultIfEmptyTransition.Create },
				{ QyMethods.DefaultIfEmpty2, DefaultIfEmpty2Transition.Create },
				{ QyMethods.Distinct, DistinctTransition.Create },
				{ QyMethods.Distinct2, Distinct2Transition.Create },
				{ QyMethods.ElementAt, ElementAtTransition.Create },
				{ QyMethods.ElementAtOrDefault, ElementAtOrDefaultTransition.Create },
				{ QyMethods.Except, ExceptTransition.Create },
				{ QyMethods.Except2, Except2Transition.Create },
				{ QyMethods.First, FirstTransition.Create },
				{ QyMethods.First2, First2Transition.Create },
				{ QyMethods.FirstOrDefault, FirstOrDefaultTransition.Create },
				{ QyMethods.FirstOrDefault2, FirstOrDefault2Transition.Create },
				{ QyMethods.GroupBy, GroupByTransition.Create },
				{ QyMethods.GroupBy2, GroupBy2Transition.Create },
				{ QyMethods.GroupBy3, GroupBy3Transition.Create },
				{ QyMethods.GroupBy4, GroupBy4Transition.Create },
				{ QyMethods.GroupBy5, GroupBy5Transition.Create },
				{ QyMethods.GroupBy6, GroupBy6Transition.Create },
				{ QyMethods.GroupBy7, GroupBy7Transition.Create },
				{ QyMethods.GroupBy8, GroupBy8Transition.Create },
				{ QyMethods.GroupJoin, GroupJoinTransition.Create },
				{ QyMethods.GroupJoin2, GroupJoin2Transition.Create },
				{ QyMethods.Intersect, IntersectTransition.Create },
				{ QyMethods.Intersect2, Intersect2Transition.Create },
				{ QyMethods.Join, JoinTransition.Create },
				{ QyMethods.Join2, Join2Transition.Create },
				{ QyMethods.Last, LastTransition.Create },
				{ QyMethods.Last2, Last2Transition.Create },
				{ QyMethods.LastOrDefault, LastOrDefaultTransition.Create },
				{ QyMethods.LastOrDefault2, LastOrDefault2Transition.Create },
				{ QyMethods.LongCount, LongCountTransition.Create },
				{ QyMethods.LongCount2, LongCount2Transition.Create },
				{ QyMethods.Max, MaxTransition.Create },
				{ QyMethods.Max2, Max2Transition.Create },
				{ QyMethods.Min, MinTransition.Create },
				{ QyMethods.Min2, Min2Transition.Create },
				{ QyMethods.OfType, OfTypeTransition.Create },
				{ QyMethods.OrderBy, OrderByTransition.Create },
				{ QyMethods.OrderBy2, OrderBy2Transition.Create },
				{ QyMethods.OrderByDescending, OrderByDescendingTransition.Create },
				{ QyMethods.OrderByDescending2, OrderByDescending2Transition.Create },
				{ QyMethods.Reverse, ReverseTransition.Create },
				{ QyMethods.Select, SelectTransition.Create },
				{ QyMethods.Select2, Select2Transition.Create },
				{ QyMethods.SelectMany, SelectManyTransition.Create },
				{ QyMethods.SelectMany2, SelectMany2Transition.Create },
				{ QyMethods.SelectMany3, SelectMany3Transition.Create },
				{ QyMethods.SelectMany4, SelectMany4Transition.Create },
				{ QyMethods.SequenceEqual, SequenceEqualTransition.Create },
				{ QyMethods.SequenceEqual2, SequenceEqual2Transition.Create },
				{ QyMethods.Single, SingleTransition.Create },
				{ QyMethods.Single2, Single2Transition.Create },
				{ QyMethods.SingleOrDefault, SingleOrDefaultTransition.Create },
				{ QyMethods.SingleOrDefault2, SingleOrDefault2Transition.Create },
				{ QyMethods.Skip, SkipTransition.Create },
				{ QyMethods.SkipWhile, SkipWhileTransition.Create },
				{ QyMethods.SkipWhile2, SkipWhile2Transition.Create },
				{ QyMethods.Sum, SumTransition.Create },
				{ QyMethods.Sum10, Sum10Transition.Create },
				{ QyMethods.Sum11, Sum11Transition.Create },
				{ QyMethods.Sum12, Sum12Transition.Create },
				{ QyMethods.Sum13, Sum13Transition.Create },
				{ QyMethods.Sum14, Sum14Transition.Create },
				{ QyMethods.Sum15, Sum15Transition.Create },
				{ QyMethods.Sum16, Sum16Transition.Create },
				{ QyMethods.Sum17, Sum17Transition.Create },
				{ QyMethods.Sum18, Sum18Transition.Create },
				{ QyMethods.Sum19, Sum19Transition.Create },
				{ QyMethods.Sum2, Sum2Transition.Create },
				{ QyMethods.Sum20, Sum20Transition.Create },
				{ QyMethods.Sum3, Sum3Transition.Create },
				{ QyMethods.Sum4, Sum4Transition.Create },
				{ QyMethods.Sum5, Sum5Transition.Create },
				{ QyMethods.Sum6, Sum6Transition.Create },
				{ QyMethods.Sum7, Sum7Transition.Create },
				{ QyMethods.Sum8, Sum8Transition.Create },
				{ QyMethods.Sum9, Sum9Transition.Create },
				{ QyMethods.Take, TakeTransition.Create },
				{ QyMethods.TakeWhile, TakeWhileTransition.Create },
				{ QyMethods.TakeWhile2, TakeWhile2Transition.Create },
				{ QyMethods.ThenBy, ThenByTransition.Create },
				{ QyMethods.ThenBy2, ThenBy2Transition.Create },
				{ QyMethods.ThenByDescending, ThenByDescendingTransition.Create },
				{ QyMethods.ThenByDescending2, ThenByDescending2Transition.Create },
				{ QyMethods.Union, UnionTransition.Create },
				{ QyMethods.Union2, Union2Transition.Create },
				{ QyMethods.Where, WhereTransition.Create },
				{ QyMethods.Where2, Where2Transition.Create },
				{ QyMethods.Zip, ZipTransition.Create },
			};

	} 

}